---
title: "OwenQ 2"
author: "Stéphane Laurent"
date: "2017-12-21"
output:
  html_document:
    keep_md: no
    toc: yes
  md_document:
    toc: yes
    variant: markdown
    preserve_yaml: true
prettify: yes
linenums: yes
prettifycss: twitter-bootstrap
tags: R, maths, statistics
highlighter: kate
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, collapse=TRUE, fig.path="./figures/OwenAlgo2-")
```


```{r}
library(OwenQ)
```

```{r}
powerTOST <- function(alpha, delta0, Delta, sigma, n1, n2, algo) {
  se <- sqrt(1/n1 + 1/n2) * sigma
  delta1 <- (delta0 + Delta) / se
  delta2 <- (delta0 - Delta) / se
  dof <- n1 + n2 - 2
  q <- qt(1 - alpha, dof)
  powen4(dof, q, -q, delta1, delta2, algo)
}
```


- For $n_1=n_2=1000$, $\alpha=0.05$, $\delta=0$, $\Delta=5$, the `powen4` function abnormally takes some negative values:

```{r, echo=FALSE, fig.width=8, fig.height=4}
par(mar=c(4,4,0.4,0.4))
layout(t(c(1,2)))
sigma <- seq(65,69,len=100)
n1 <- 1000; n2 <- 1000
plot(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 1L), type="l", lwd=2, 
     xlab=expression(sigma), ylab="power")
lines(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 2L), col="blue", lwd=2)
abline(h=0, col="red", lty=2)
legend("topright", c("algo1", "algo2"), lty=c(1,1), col=c("black", "blue"))
sigma <- seq(15,69,len=100)
plot(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 1L), type="l", lwd=2, 
     xlab=expression(sigma), ylab="power")
lines(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 2L), col="blue", lwd=2)
abline(h=0, col="red", lty=2)
legend("topright", c("algo1", "algo2"), lty=c(1,1), col=c("black", "blue"))
```


- For $n_1=n_2=720$, $\alpha=0.05$, $\delta=0$, $\Delta=5$:

```{r, echo=FALSE, fig.width=4, fig.height=4}
par(mar=c(4,4,0.4,0.4))
n1 <- n2 <- 720
sigma <- seq(56,57,len=100)
plot(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 1L), type="l", lwd=2, 
     xlab=expression(sigma), ylab="power")
lines(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 2L), col="blue", lwd=2)
legend("topright", c("algo1", "algo2"), lty=c(1,1), col=c("black", "blue"))
```


- For $n_1=n_2=700$, $\alpha=0.01$, $\delta=0$, $\Delta=5$:

```{r, echo=FALSE, fig.width=8, fig.height=4}
par(mar=c(4, 4, 0.2, 0.2))
layout(t(c(1,2)))
n1 <- n2 <- 700
sigma <- seq(35,45,len=100)
plot(sigma, powerTOST(0.01, 1, 5, sigma, n1, n2, 1L), type="l", lwd=2, 
     xlab=expression(sigma), ylab="power")
lines(sigma, powerTOST(0.01, 1, 5, sigma, n1, n2, 2L), col="blue", lwd=2)
legend("topright", c("algo1", "algo2"), lty=c(1,1), col=c("black", "blue"))
n1 <- n2 <- 700
sigma <- seq(38.5,39,len=100)
plot(sigma, powerTOST(0.01, 1, 5, sigma, n1, n2, 1L), type="l", lwd=2, 
     xlab=expression(sigma), ylab="power")
lines(sigma, powerTOST(0.01, 1, 5, sigma, n1, n2, 2L), col="blue", lwd=2)
legend("topright", c("algo1", "algo2"), lty=c(1,1), col=c("black", "blue"))
```



- For $\boxed{n_1=n_2=5000}$, $\alpha=0.05$, $\delta=0$, $\Delta=5$:

```{r, echo=FALSE, fig.width=4, fig.height=4}
par(mar=c(4,4,0.4,0.4))
n1 <- n2 <- 5000
sigma <- seq(50,200,len=100)
plot(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 1L), type="l", lwd=2, 
     xlab=expression(sigma), ylab="power")
lines(sigma, powerTOST(0.05, 0, 5, sigma, n1, n2, 2L), col="blue", lwd=2)
legend("topright", c("algo1", "algo2"), lty=c(1,1), col=c("black", "blue"))
```
